apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr

  template:
    metadata:
      labels:
        app: sonarr

    spec:
      containers:
        - name: sonarr
          # All tags:
          # https://github.com/linuxserver/docker-sonarr/pkgs/container/sonarr/versions?filters%5Bversion_type%5D=tagged
          image: linuxserver/sonarr:4.0.10
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: backups
              mountPath: /backups
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data

      volumes:
        - name: backups
          persistentVolumeClaim:
            claimName: nfs-media-backups
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config-claim
        - name: media
          persistentVolumeClaim:
            claimName: nfs-media
