homepage:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - host: &host homepage.proxy2.lan.qidux.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

  config:
    kubernetes:
      mode: cluster

    widgets:
      - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
