homepage:
  image:
    tag: v0.9.11

  ingress:
    main:
      enabled: true
      hosts:
        - host: &host proxy2.lan.qidux.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: lan-wildcard-tls

  config:
    bookmarks: []

    services:
      - Media:
        - Plex:
            icon: plex
            href: http://plex.lan.qidux.com:32400/web
            description: Watch movies and TV shows.
      - Management:
        - Sonarr:
            icon: sonarr
            href: https://sonarr.proxy2.lan.qidux.com
            description: Manage TV shows.
        - Radarr:
            icon: radarr
            href: https://radarr.proxy2.lan.qidux.com
            description: Manage movies.
        - Prowlarr:
            icon: prowlarr
            href: https://prowlarr.proxy2.lan.qidux.com
            description: Manage indexers.
        - SABnzbd:
            icon: sabnzbd
            href: https://sabnzbd.proxy.lan.qidux.com
            description: Manage downloads.

    widgets: []

