homepage:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - host: &host homepage.proxy2.lan.qidux.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

  config:
    services:
      - Media:
        - Plex:
            icon: plex.png
            href: http://plex.lan.qidux.com:32400/web
            description: Watch movies and TV shows.

