---
- name: Install Docker prerequisites
  become: true
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest

- name: Add Docker GPG key
  become: true
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg

- name: Add Docker apt repository
  become: true
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  become: true
  apt:
    # Docker recommends the `aufs-dkms` package which does not build on
    # Raspbian.
    install_recommends: false
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Add remote user to `docker` group
  become: true
  user:
    append: true
    groups: docker
    name: "{{ ansible_user_id }}"

- name: Install dependencies for Ansible to use pip
  become: true
  package:
    name:
      - python3-pip
      - python3-setuptools
    state: present

- name: Install `docker` python module
  become: true
  pip:
    name: docker
    state: latest
