---
- name: Install Docker prerequisites
  become: true
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Create apt keyrings directory
  become: true
  ansible.builtin.file:
    mode: '755'
    path: /etc/apt/keyrings
    state: directory

- name: Download Docker GPG key
  become: true
  ansible.builtin.get_url:
    dest: /etc/apt/keyrings/docker.gpg_armored
    force: true
    mode: '644'
    url: https://download.docker.com/linux/debian/gpg
  register: docker_gpg_download

- name: Add Docker GPG key to apt keyring
  become: true
  ansible.builtin.shell: gpg --dearmor -o /etc/apt/keyrings/docker.gpg < /etc/apt/keyrings/docker.gpg_armored
  args:
    # We want to run the command only if a new GPG key was downloaded or if the
    # unarmored key doesn't exist.
    creates: "{{ omit if docker_gpg_download.changed else '/etc/apt/keyrings/docker.gpg'}}"

- name: Add Docker apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
  vars:
    deb_architecture:
      x86_64: amd64

- name: Install Docker
  become: true
  ansible.builtin.package:
    name:
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
