nomad_architecture: linux_amd64
nomad_archive: "nomad_{{ nomad_version }}_{{ nomad_architecture }}.zip"
nomad_version: "1.4.4"
nomad_checksum: sha256:63bbb4c1d7c3da7a68dd1e3eed301a4edecf0930b2c5efe4940200ed9c73e350

nomad_install_dir: /opt/nomad
nomad_binary_dir: "{{ nomad_install_dir }}/bin"
nomad_config_dir: /etc/nomad.d
nomad_data_dir: "{{ nomad_install_dir }}/data"

nomad_mode: client
nomad_user: nomad
nomad_operator: "{% if nomad_mode == 'server' %}{{ nomad_user }}{% else %}root{% endif %}"
