nomad_arch_map:
  aarch64: arm64
  x86_64: amd64

nomad_architecture: linux_{{ nomad_arch_map[ansible_architecture] }}
nomad_archive: "nomad_{{ nomad_version }}_{{ nomad_architecture }}.zip"
nomad_version: "1.6.3"

nomad_checksums:
  linux_amd64: sha256:1771f83030d9c0e25b4b97b73e824f4b566721e3b9898ae9940eceb95bb7f4d0
  linux_arm64: sha256:1b85902b62fcaf992c98f6c3970742608c919d2d2e8db59933702859600b866e
nomad_checksum: "{{ nomad_checksums[nomad_architecture] }}"

nomad_install_dir: /opt/nomad
nomad_binary_dir: "{{ nomad_install_dir }}/bin"
nomad_config_dir: /etc/nomad.d
nomad_data_dir: "{{ nomad_install_dir }}/data"

nomad_mode: client
nomad_user: nomad
nomad_operator: "{% if nomad_mode == 'server' %}{{ nomad_user }}{% else %}root{% endif %}"

nomad_volumes: []
nomad_client_meta: {}

nomad_enable_raw_exec: false
