---
- name: Download Kubeconfig
  hosts: k3s_server
  remote_user: provisioning

  tasks:
    - name: Copy kubeconfig
      become: true
      run_once: true
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../platform/kubeconfig.yaml
        flat: true

    - name: Replace server IP
      delegate_to: localhost
      run_once: true
      ansible.builtin.replace:
        path: ../platform/kubeconfig.yaml
        regexp: '^(\s+server: https://)127.0.0.1'
        replace: '\g<1>{{ play_hosts[0] }}'
