---
- name: K8s Server
  hosts: k8s_server
  become: true

  roles:
    - name: k3s.orchestration.k3s_server

- name: K8s Agents
  hosts: k8s_agents
  become: true

  roles:
    - name: k3s.orchestration.k3s_agent

- name: Common utilities
  hosts: k8s
  become: true

  tasks:
    - name: Install NFS client
      ansible.builtin.package:
        name: nfs-common
        state: present

- name: Node exporter
  hosts: metal
  become: true

  roles:
    - name: node-exporter
      version: "1.8.2"
      checksums:
        amd64: "6809dd0b3ec45fd6e992c19071d6b5253aed3ead7bf0686885a51d85c6643c66"
        arm64: "627382b9723c642411c33f48861134ebe893e70a63bcc8b3fc0619cd0bfac4be"
