---
- name: K3s Server
  hosts: k3s_server
  remote_user: provisioning
  become: true

  roles:
    - name: k3s.orchestration.k3s_server

- name: K3s Agents
  hosts: k3s_agents
  remote_user: provisioning
  become: true

  roles:
    - name: k3s.orchestration.k3s_agent

- name: Common utilities
  hosts: all
  remote_user: provisioning
  become: true

  tasks:
    - name: Install NFS client
      ansible.builtin.package:
        name: nfs-common
        state: present
