- name: Reload Nomad
  become: true
  ansible.builtin.service:
    name: nomad
    state: reloaded

- name: Restart Nomad
  become: true
  ansible.builtin.service:
    name: nomad
    state: restarted
