---
- name: Create Ansible user
  become: true
  remote_user: pi
  vars:
    ansible_ssh_pass: raspberry
  user:
    groups: sudo
    name: ansible

- name: Enable password-less sudo
  become: true
  remote_user: pi
  vars:
    ansible_ssh_pass: raspberry
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^ansible ALL='
    line: 'ansible ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: Add authorized keys
  become: true
  remote_user: pi
  vars:
    ansible_ssh_pass: raspberry
  authorized_key:
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    state: present
    user: ansible

# Without enabling PAM, the password-less ansible user cannot log in.
- name: Enable PAM for SSH
  become: true
  remote_user: pi
  vars:
    ansible_ssh_pass: raspberry
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?UsePAM"
    line: UsePAM yes
    validate: sshd -t -f %s
  notify: restart_sshd
