---
- name: Update hostname
  block:
    - name: Add new hostname to /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.1.1\t{{ desired_hostname }}"
        owner: root
        group: root
        mode: '0644'

    - name: Set hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ desired_hostname }}"

    - name: Remove old hostnames from /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+(?!{{ desired_hostname }}).+$'
        state: absent
        owner: root
        group: root
        mode: '0644'

  when: desired_hostname is defined
