- name: Install dependencies
  become: true
  ansible.builtin.package:
    name:
      - firefox-esr
      - xdotool

- name: Download controller archive
  become: true
  ansible.builtin.get_url:
    checksum: "{{ magic_mirror_kiosk_controller_checksum }}"
    dest: /opt/{{ magic_mirror_kiosk_controller_archive }}
    url: "{{ magic_mirror_kiosk_controller_archive_url }}"

- name: Create controller bin directory
  become: true
  ansible.builtin.file:
    mode: "755"
    path: "{{ magic_mirror_kiosk_controller_bin_dir }}"
    state: directory

- name: Unpack controller archive
  become: true
  ansible.builtin.unarchive:
    dest: "{{ magic_mirror_kiosk_controller_bin_dir }}"
    include:
      - magic-mirror-controller
    remote_src: true
    src: "/opt/{{ magic_mirror_kiosk_controller_archive }}"

- name: Create user service directory
  become: true
  ansible.builtin.file:
    path: "/home/pi/.config/systemd/user"
    state: directory
    owner: pi
    mode: "755"

- name: Upload controller service
  become: true
  ansible.builtin.template:
    dest: "/home/pi/.config/systemd/user/magic-mirror-controller.service"
    mode: "644"
    owner: pi
    src: magic-mirror-controller.service
  notify:
    - Restart mirror

- name: Upload kiosk service
  become: true
  ansible.builtin.template:
    dest: "/home/pi/.config/systemd/user/magic-mirror-kiosk.service"
    mode: "644"
    owner: pi
    src: magic-mirror-kiosk.service
  notify:
    - Restart mirror

- name: Start kiosk at login
  become: true
  ansible.builtin.blockinfile:
    path: /home/pi/.config/wayfire.ini
    block: |
      [autostart]
      kiosk = systemctl start --user magic-mirror-kiosk.service
      kisok-controller = systemctl start --user magic-mirror-controller.service
      screensaver = false
      dpms = false
  notify:
    - Restart mirror
