---
- name: Install sudo utility
  become: true
  remote_user: "{{ original_user }}"
  vars:
    ansible_ssh_pass: "{{ original_password }}"
  ansible.builtin.package:
    name: sudo
    state: present

- name: Create Ansible user
  become: true
  remote_user: "{{ original_user }}"
  vars:
    ansible_ssh_pass: "{{ original_password }}"
  user:
    groups: sudo
    name: ansible

- name: Enable password-less sudo
  become: true
  remote_user: "{{ original_user }}"
  vars:
    ansible_ssh_pass: "{{ original_password }}"
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^ansible ALL='
    line: 'ansible ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: Create SSH directory
  become: true
  remote_user: "{{ original_user }}"
  vars:
    ansible_ssh_pass: "{{ original_password }}"
  ansible.builtin.file:
    path: /home/ansible/.ssh
    state: directory
    mode: "700"
    owner: ansible
    group: ansible

- name: Add authorized keys
  become: true
  remote_user: "{{ original_user }}"
  vars:
    ansible_ssh_pass: "{{ original_password }}"
  ansible.builtin.get_url:
    url: "{{ authorized_keys_url }}"
    dest: /home/ansible/.ssh/authorized_keys
    mode: "644"
    owner: ansible
    group: ansible

# Without enabling PAM, the password-less ansible user cannot log in.
- name: Enable PAM for SSH
  become: true
  remote_user: "{{ original_user }}"
  vars:
    ansible_ssh_pass: "{{ original_password }}"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?UsePAM"
    line: UsePAM yes
    validate: sshd -t -f %s
  notify: restart_sshd
