---
- name: Create Pi-hole user
  become: true
  ansible.builtin.user:
    create_home: false
    name: pihole

- name: Create Pi-hole config directory
  become: true
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    mode: "775"
    owner: pihole
    group: pihole

- name: Configure Pi-hole
  become: true
  template:
    dest: /etc/pihole/setupVars.conf
    group: root
    mode: "644"
    owner: root
    src: setupVars.conf.j2
  notify: reload pihole

- name: Upload local DNS records
  become: true
  ansible.builtin.copy:
    dest: /etc/pihole/custom.list
    group: pihole
    mode: "644"
    owner: pihole
    src: custom.list

- name: Download Pi-hole installer
  become: true
  ansible.builtin.get_url:
    url: https://install.pi-hole.net
    dest: /opt/pi-hole-installer.sh
    force: false
    mode: "755"

- name: Install Pi-hole
  ansible.builtin.command: /opt/pi-hole-installer.sh --unattended
  args:
    creates: /usr/local/bin/pihole
  register: pi_hole_install

- name: Update Pi-hole
  command: pihole -up
  when: not pi_hole_install.changed
  register: pi_hole_update
  changed_when: "'update_available' in pi_hole_update.stdout"
