apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
