apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
  label:
    app: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  # There can only be one primary server at a time, so we need to shut down
  # before spinning up a new pod.
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-env
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data-claim
