apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-school
  namespace: flight-school
  labels:
    app: flight-school

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-school

  template:
    metadata:
      labels:
        app: flight-school

    spec:
      containers:
        - name: flight-school
          image: &image ghcr.io/cdriehuys/flight-school:v0.2.0
          command: ["--debug"]
          ports:
            - containerPort: 8000
              name: http

          env:
            - name: FLIGHT_SCHOOL_DSN
              valueFrom:
                secretKeyRef:
                  name: flight-school-env
                  key: dsn

      initContainers:
        - name: flight-school-migrate
          image: *image
          command: ["migrate"]

          env:
            - name: FLIGHT_SCHOOL_DSN
              valueFrom:
                secretKeyRef:
                  name: flight-school-env
                  key: dsn
