---
- name: Update authorized keys
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/authorized_keys"
    dest: /home/ansible/.ssh/authorized_keys
    mode: "600"
    owner: ansible
    group: ansible

- name: Disable SSH challenge response authentication
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?ChallengeResponseAuthentication"
    line: ChallengeResponseAuthentication no
    validate: sshd -t -f %s
  notify: restart_sshd

- name: Disable SSH password authentication
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: PasswordAuthentication no
    validate: sshd -t -f %s
  notify: restart_sshd

- name: Disable SSH root login
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: PermitRootLogin no
    validate: sshd -t -f %s
  notify: restart_sshd
