k3s_version: "v1.32.1+k3s1"
# Disable CNI plugin and network policy enforcer to allow for installing
# Cilium later.
extra_server_args: "--flannel-backend=none --disable-network-policy"
extra_agent_args: ""

token: "change-me-later"
api_endpoint: "{{ groups['k8s_server'][0] }}"

server_group: k8s_server
