k3s_version: "v1.31.1+k3s1"
# Disable CNI plugin and network policy enforcer to allow for installing
# Cilium later.
extra_server_args: "--flannel-backend=none --disable-network-policy"
extra_agent_args: ""

token: "change-me-later"
api_endpoint: "{{ groups['k3s_server'][0] }}"

server_group: k3s_server
