- hosts: localhost
  gather_facts: false

  vars:
    instance_cores: 1
    instance_cpuunits: 1000
    instance_node: pve
    instance_ostemplate: local:vztmpl/debian-11-standard_11.6-1_amd64.tar.zst
    proxmox_host: pve.lan.qidux.com:8006

  roles:
    - role: proxmox-instance
      action: create
      instance_type: lxc
      instance_hostname: consul1
      instance_password: abcde
    - role: proxmox-instance
      action: create
      instance_type: lxc
      instance_hostname: consul2
      instance_password: abcde
    - role: proxmox-instance
      action: create
      instance_type: lxc
      instance_hostname: consul3
      instance_password: abcde

    - role: proxmox-instance
      action: delete
      instance_hostname: consul1
      instance_type: lxc
    - role: proxmox-instance
      action: delete
      instance_hostname: consul2
      instance_type: lxc
    - role: proxmox-instance
      action: delete
      instance_hostname: consul3
      instance_type: lxc
