version: "3.7"

services:
  ansible:
    build:
      context: .
    image: ansible

    command:
      - "ansible-playbook"
      - "-i"
      - "./inventory.ini"
      - "site.yml"

    environment:
      ANSIBLE_VAULT_PASSWORD_FILE: "./.vault_password"

    volumes:
      - "./:/opt/provisioning/"
      - "~/.ssh/id_rsa:/root/.ssh/id_rsa"
      - "~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub"
