version: "3.7"

services:
  ansible:
    build:
      context: .
    image: ansible

    environment:
      ANSIBLE_VAULT_PASSWORD_FILE: "./.vault_password"

    volumes:
      - "./:/opt/provisioning/"
      - "~/.ssh:/root/.ssh:ro"
