- name: Create admin users
  gather_facts: false
  hosts: magic_mirror
  # We need to attempt a login with the admin user to check if these tasks need
  # to run. In order to do that, we need to be able to handle an unreachable
  # host.
  ignore_unreachable: true
  remote_user: ansible

  roles:
    - role: provisioning-user
      original_user: pi
      original_password: raspberry

- name: Provision magic mirror client
  hosts: magic_mirror
  remote_user: ansible

  roles:
    - ssh-harden
    - role: key-sync
      vars:
        key_sync_url: "{{ authorized_keys_url }}"
    - role: consul
      consul_mode: agent
    - role: magic-mirror-kiosk
      vars:
        magic_mirror_kiosk_url: https://magic-mirror.proxy.lan.qidux.com
    - role: consul-service-register
      vars:
        consul_service_name: magic-mirror-controller
        consul_service_port: 8080
        consul_service_hostname: mm-controller.proxy.lan.qidux.com
        consul_service_checks:
          - path: "/display-state"
