- hosts: localhost
  gather_facts: false

  vars:
    instance_cores: 1
    instance_cpuunits: 1000
    instance_node: pve
    instance_ostemplate: local:vztmpl/debian-11-with-ssh_11.6-1_amd64.tar.zst
    proxmox_host: pve.{{ local_domain }}:8006

  roles:
    - role: proxmox-instance
      action: create
      instance_hostname: nomad1
      instance_password: abcde
      instance_type: lxc
    - role: proxmox-instance
      action: create
      instance_hostname: nomad2
      instance_password: abcde
      instance_type: lxc
    - role: proxmox-instance
      action: create
      instance_hostname: nomad3
      instance_password: abcde
      instance_type: lxc

- name: Create admin users
  gather_facts: false
  hosts: nomad
  # We need to attempt a login with the admin user to check if these tasks need
  # to run. In order to do that, we need to be able to handle an unreachable
  # host.
  ignore_unreachable: true
  remote_user: ansible

  roles:
    - role: provisioning-user
      original_user: root
      original_password: abcde

- name: Install Nomad node prerequisites
  hosts: nomad
  remote_user: ansible

  roles:
    - ssh-harden
    - role: key-sync
      vars:
        key_sync_url: "{{ authorized_keys_url }}"
    - role: consul
      consul_mode: agent

- name: Provision Nomad servers
  hosts: nomad_servers
  remote_user: ansible

  roles:
    - role: nomad
      nomad_mode: server

- name: Provision Nomad client agents
  hosts: nomad_clients
  remote_user: ansible

  vars:
    nomad_volumes:
      - name: home-assistant
        path: /nfs/nomad/home-assistant
        read_only: false

  pre_tasks:
    - name: Install NFS packages
      become: true
      ansible.builtin.package:
        name: nfs-common
        state: present
    - name: Mount NAS
      become: true
      ansible.posix.mount:
        boot: true
        fstype: nfs
        opts: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800,x-systemd.automount
        path: /nfs/nomad
        src: freenas.lan.qidux.com:/mnt/Primary/nomad
        state: mounted
    - name: Ensure Nomad volume directories exist
      become: true
      ansible.builtin.file:
        mode: "755"
        path: "{{ item.path }}"
        state: directory
      loop: "{{ nomad_volumes }}"

  roles:
    - docker
    - role: nomad
      nomad_mode: client
      nomad_volumes:
        - name: home-assistant
          path: /nfs/nomad/home-assistant
          read_only: false
        - name: traefik
          path: /nfs/nomad/traefik
          read_only: false
