- name: DNS
  ansible.builtin.import_playbook: dns.yml

- name: Consul
  ansible.builtin.import_playbook: consul.yml

- name: Vault
  ansible.builtin.import_playbook: vault.yml

- name: Nomad
  ansible.builtin.import_playbook: nomad.yml

- name: Magic Mirror
  ansible.builtin.import_playbook: magic-mirror.yml
