- name: Restart Magic Mirror controller
  become: true
  ansible.builtin.service:
    name: magic-mirror-controller
    state: restarted

- name: Restart Magic Mirror kiosk
  become: true
  ansible.builtin.service:
    name: magic-mirror-kiosk
    state: restarted

- name: Restart mirror
  become: true
  ansible.builtin.reboot:
