apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
